version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - microservice-network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "R@min5402"  
    ports:
      - "1433:1433"
    networks:
      - microservice-network

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - microservice-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet_eventstore_db
    ports:
      - "5432:5432"
    networks:
      - microservice-network

  mongodb:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - microservice-network

  database-proxy-service:
    build:
      context: ./services/database-proxy
      dockerfile: Dockerfile
    ports:
      - "1434:1434"
    container_name: database-proxy-service
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
      - billing-service
    environment:
      - PROXY_LISTEN_PORT=${DATABASE_PROXY__PROXY__LISTEN_PORT}
      - PROXY_DESTINATION_HOST=${DATABASE_PROXY__PROXY__DESTINATION_HOST}
      - PROXY_DESTINATION_PORT=${DATABASE_PROXY__PROXY__DESTINATION_PORT}

      - REDIS_ADDRESS=${DATABASE_PROXY__REDIS__ADDRESS}
      - REDIS_PASSWORD=${DATABASE_PROXY__REDIS__PASSWORD}
      - REDIS_DB=${DATABASE_PROXY__REDIS__DB}

      - RABBITMQ_HOST=${DATABASE_PROXY__RABBITMQ__HOST}
      - RABBITMQ_PORT=${DATABASE_PROXY__RABBITMQ__PORT}
      - RABBITMQ_USERNAME=${DATABASE_PROXY__RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${DATABASE_PROXY__RABBITMQ__PASSWORD}

      - BILLING_SERVICE_HOST=${DATABASE_PROXY__BILLING_SERVICE__HOST}
      - BILLING_SERVICE_PORT=${DATABASE_PROXY__BILLING_SERVICE__PORT}

      - CERTIFICATE_FILE=${DATABASE_PROXY__CERTIFICATE__FILE}
    volumes:
      - ./certificates:/app/certificates
    networks:
      - microservice-network

  billing-service:
    build:
      context: ./services/billing
      dockerfile: Dockerfile
    container_name: billing-service
    depends_on:
      - sqlserver
      - rabbitmq
      - wallet-service
    environment:
      - CONNECTIONSTRINGS__BILLING=${BILLING_SERVICE__CONNECTIONSTRINGS__BILLING}

      - EXTERNALSERVICESSETTING__WALLET__NAME=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__NAME}
      - EXTERNALSERVICESSETTING__WALLET__BASEURL=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__BASEURL}
      - EXTERNALSERVICESSETTING__WALLET__TIMEOUTINSECONDS=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__TIMEOUTINSECONDS}
      - EXTERNALSERVICESSETTING__WALLET__CREATEWALLET=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__CREATEWALLET}
      - EXTERNALSERVICESSETTING__WALLET__WITHDRAW=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__WITHDRAW}
      - EXTERNALSERVICESSETTING__WALLET__GETWALLET=${BILLING_SERVICE__EXTERNALSERVICESSETTING__WALLET__GETWALLET}

      - EVENTBUSSETTING__CONNECTIONSETTING__HOSTNAME=${BILLING_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__HOSTNAME}
      - EVENTBUSSETTING__CONNECTIONSETTING__PORT=${BILLING_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__PORT}
      - EVENTBUSSETTING__CONNECTIONSETTING__USERNAME=${BILLING_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__USERNAME}
      - EVENTBUSSETTING__CONNECTIONSETTING__PASSWORD=${BILLING_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__PASSWORD}
      - EVENTBUSSETTING__CONNECTIONSETTING__VIRTUALHOST=${BILLING_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__VIRTUALHOST}

      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__NAME=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__NAME}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__TYPE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__TYPE}

      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__NAME=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__NAME}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__ROUTINGKEY=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__DURABLE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__DURABLE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__AUTODELETE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__AUTODELETE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__EXCLUSIVE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__TTL=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__TTL}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__PREFETCHCOUNT=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__EXPIRETIME=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__NAME=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__NAME}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__ROUTINGKEY=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__DURABLE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__DURABLE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__AUTODELETE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__AUTODELETE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__EXCLUSIVE=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__TTL=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__TTL}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSEXCHANGE__RETRYQUEUE__PREFETCHCOUNT=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSEXCHANGE__RETRYQUEUE__EXPIRETIME=${BILLING_SERVICE__EVENTBUSSETTING__QUERYPAYUSAGEEVENTSEXCHANGE__QUERYPAYUSAGEEVENTSQUEUE__RETRYQUEUE__EXPIRETIME}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Certificates__Default__Password}
    ports:
      - "5161:5161"
    volumes:
      - ./certificates:/app/certificates
    networks:
      - microservice-network

  wallet-service:
    build:
      context: ./services/wallet
      dockerfile: Dockerfile
    container_name: wallet-service
    depends_on:
      - rabbitmq
      - postgres
      - mongodb
    environment:
      - CONNECTIONSTRINGS__EVENTSTORE=${WALLET_SERVICE__CONNECTIONSTRINGS__EVENTSTORE}
      - CONNECTIONSTRINGS__READMODEL=${WALLET_SERVICE__CONNECTIONSTRINGS__READMODEL}

      - EVENTBUSSETTING__CONNECTIONSETTING__HOSTNAME=${WALLET_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__HOSTNAME}
      - EVENTBUSSETTING__CONNECTIONSETTING__PORT=${WALLET_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__PORT}
      - EVENTBUSSETTING__CONNECTIONSETTING__USERNAME=${WALLET_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__USERNAME}
      - EVENTBUSSETTING__CONNECTIONSETTING__PASSWORD=${WALLET_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__PASSWORD}
      - EVENTBUSSETTING__CONNECTIONSETTING__VIRTUALHOST=${WALLET_SERVICE__EVENTBUSSETTING__CONNECTIONSETTING__VIRTUALHOST}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__TYPE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__TYPE}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETCREATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETTRANSACTIONCREATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__EXPIRETIME}

      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__NAME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__NAME}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__ROUTINGKEY}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__DURABLE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__DURABLE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__AUTODELETE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__EXCLUSIVE}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__TTL=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__TTL}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__PREFETCHCOUNT}
      - EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME=${WALLET_SERVICE__EVENTBUSSETTING__WALLETINTEGRATIONEVENTSEXCHANGE__WALLETUPDATEDEVENTQUEUE__RETRYQUEUE__EXPIRETIME}
    ports:
      - "5100:5100"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge