proxy:
  listen_port: 1434
  destination_host: "127.0.0.1"
  destination_port: 1433
redis:
  address: "localhost:6375"
  password: ""
  db: 0
rabbitmq:
  host: "localhost"
  port: 5672
  username: "admin"
  password: "admin"
billing_service:
  host: "localhost"
  port: 5161
certificate:
  file: "localhost.crt"
